services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: bigo-grafana
    restart: unless-stopped
    volumes:
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-config/provisioning:/etc/grafana/provisioning
    ports:
     - '3000:3000'

  prometheus:
    image: prom/prometheus:latest
    container_name: bigo-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
  postgres:
    image: postgres:latest
    container_name: bigo-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
