{
 "title": "BigO Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_client_request_duration_seconds_bucket[1m]))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(http_client_request_duration_seconds_bucket[1m]))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Reqs/Sec Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_client_requests_total[30s])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_client_requests_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_client_request_errors_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req/Sec",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_client_requests_total[30s])",
     "legendFormat": "{{server_addr}}"
    },
    {
     "expr": "sum(rate(http_client_requests_total[30s]))",
     "legendFormat": "Req/Sec (All servers)"
    }
   ]
  }
 ]
}